// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNbvB5Q46XSnA9ryXA6OTp7OyPPum53uM',
    appId: '1:710026785801:web:51c2c5c2defa84fdb6f4d8',
    messagingSenderId: '710026785801',
    projectId: 'taskapp-ee8c9',
    authDomain: 'taskapp-ee8c9.firebaseapp.com',
    storageBucket: 'taskapp-ee8c9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0aj9he7cVTLiuqKigFO6eI8ZXlqGZuHU',
    appId: '1:710026785801:android:2b7217690c0d0d3db6f4d8',
    messagingSenderId: '710026785801',
    projectId: 'taskapp-ee8c9',
    storageBucket: 'taskapp-ee8c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjNW8cqIMN1nmcX_DDS1ntUp630yXfVgY',
    appId: '1:710026785801:ios:0ef18fb8b93c386ab6f4d8',
    messagingSenderId: '710026785801',
    projectId: 'taskapp-ee8c9',
    storageBucket: 'taskapp-ee8c9.appspot.com',
    iosClientId: '710026785801-bd5tb7iff2a81ukqo6og0btkr4u610h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjNW8cqIMN1nmcX_DDS1ntUp630yXfVgY',
    appId: '1:710026785801:ios:0ef18fb8b93c386ab6f4d8',
    messagingSenderId: '710026785801',
    projectId: 'taskapp-ee8c9',
    storageBucket: 'taskapp-ee8c9.appspot.com',
    iosClientId: '710026785801-bd5tb7iff2a81ukqo6og0btkr4u610h0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
